### ISSUE TITLE
Order PDF fail to print when having any bundled items in order.

### ISSUE THREAD

**Issue by natawut-ch** [fooman/printorderpdf-m2#1]
Symptom ::
When having bundled-item in orders, rendering will fail, provide no PDF.

My investigation ::
in vendor/fooman/printorderpdf-m2/Model/Pdf/Order.php , $item in
`$this->_drawItem($item, $page, $order);`
will be InstanceOf Magento\Sales\Model\Order\Item

In \Magento\Sales\Model\Order\Pdf\Items\AbstractItems abstract class
when calling getChildren Magento will check instance type and 
Magento\Sales\Model\Order\Item is not there, leading the variable $items become null. causing script to fail.
```
abstract class AbstractItems extends \Magento\Sales\Model\Order\Pdf\Items\AbstractItems
{
    /**
     * Getting all available children for Invoice, Shipment or CreditMemo item
     *
     * @param \Magento\Framework\DataObject $item
     * @return array
     */
    public function getChildren($item)
    {
        $itemsArray = [];

        $items = null;
        if ($item instanceof \Magento\Sales\Model\Order\Invoice\Item) {
            $items = $item->getInvoice()->getAllItems();
        } elseif ($item instanceof \Magento\Sales\Model\Order\Shipment\Item) {
            $items = $item->getShipment()->getAllItems();
        } elseif ($item instanceof \Magento\Sales\Model\Order\Creditmemo\Item) {
            $items = $item->getCreditmemo()->getAllItems();
        }
```

```
Stack Trace ::

a:4:{i:0;s:176:"Warning: Invalid argument supplied for foreach() in ../magento2/vendor/magento/module-bundle/Model/Sales/Order/Pdf/Items/Invoice.php on line 78";i:1;s:6013:"#0 ../magento2/vendor/magento/module-bundle/Model/Sales/Order/Pdf/Items/Invoice.php(78): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/var/www/client...', 78, Array)
#1 ../magento2/vendor/magento/module-sales/Model/Order/Pdf/AbstractPdf.php(839): Magento\Bundle\Model\Sales\Order\Pdf\Items\Invoice->draw()
#2 ../magento2/vendor/fooman/printorderpdf-m2/Model/Pdf/Order.php(66): Magento\Sales\Model\Order\Pdf\AbstractPdf->_drawItem(Object(Magento\Sales\Model\Order\Item), Object(Zend_Pdf_Page), Object(Magento\Sales\Model\Order))
#3 ../magento2/vendor/fooman/printorderpdf-m2/Controller/Adminhtml/Order/PrintAction.php(80): Fooman\PrintOrderPdf\Model\Pdf\Order->getPdf(Array)
#4 ../magento2/var/generation/Fooman/PrintOrderPdf/Controller/Adminhtml/Order/PrintAction/Interceptor.php(24): Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction->execute()
#5 ../magento2/vendor/magento/framework/App/Action/Action.php(102): Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor->execute()
#6 ../magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 ../magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#8 ../magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor->___callParent('dispatch', Array)
#9 ../magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Fooman\\PrintOrd...', 'dispatch', Object(Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor), Array, 'adminAuthentica...')
#10 ../magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 ../magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 ../magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Fooman\\PrintOrd...', 'dispatch', Object(Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor), Array, 'adminMassaction...')
#13 ../magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 ../magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 ../magento2/var/generation/Fooman/PrintOrderPdf/Controller/Adminhtml/Order/PrintAction/Interceptor.php(39): Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor->___callPlugins('dispatch', Array, Array)
#16 ../magento2/vendor/magento/framework/App/FrontController.php(55): Fooman\PrintOrderPdf\Controller\Adminhtml\Order\PrintAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))

```

Ps, I'm new to magento development, I tried to provide as much as I can here.

**Comment by fooman** [comment]
Thanks for the report - can you please upgrade to version 2.1.0 which should add support for bundled items
